name: release-docker
on:
  release:
    types: published

jobs:
  docker-image-alpine:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Docker meta alpine
        id: meta_alpine
        uses: docker/metadata-action@v4
        with:
          images: joseluisq/paket
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Prepare Docker envs
        shell: bash
        run: |
          echo "PAKET_VERSION=${GITHUB_REF##*/v}" >> $GITHUB_ENV
          echo "SERVER_DOCKERFILE=./docker/alpine/Dockerfile" >> $GITHUB_ENV
      -
        name: Build and push (alpine)
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64,linux/386
          file: ${{ env.SERVER_DOCKERFILE }}
          tags: ${{ steps.meta_alpine.outputs.tags }}
          build-args: |
            PAKET_VERSION=${{ env.PAKET_VERSION }}
